version: "3.9" # optional since v1.27.0
services:
#nginx
  web:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    image: ocielgp/php-fpm-mysqli:latest
    volumes:
      - ./html:/var/www/html

    # mysql
  mysql:
    image: mysql:8.0.29
    #container_name: mysql8-container
    ports:
        - "4306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
         MYSQL_ROOT_PASSWORD: TheSliver_12

